import type { Metadata } from "next";
import {
  BBH_Bartle,
  Boldonse,
  Geist,
  Geist_Mono,
  Outfit,
} from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import SmoothScroll from "@/components/SmoothScroll";

const boldonse = Boldonse({
  weight: "400",
  variable: "--font-boldonse",
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["400", "500"],
});
const bartie = BBH_Bartle({
  variable: "--font-bartie",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${boldonse.variable} ${outfit.variable} ${bartie.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main>
          <SmoothScroll>
            <Header />
            {children}
            <Footer />
          </SmoothScroll>
        </main>
      </body>
    </html>
  );
}
